version: "3.3"
services:
  app:
    image: edhriacr2022.azurecr.io/ms-frontend:1.0
    ports:
      - 3000:3000
    networks:
      - micro_service

networks:
  micro_service:
    external:
      name: micro_service