version: "3.3"
services:
  app:
    image: edhriacr2022.azurecr.io/ms-shopping-cart:1.0
    ports:
      - 3002:3002
    networks:
      - micro_service

networks:
  micro_service:
    external:
      name: micro_service