version: "3.3"
services:
  app:
    image: edhriacr2022.azurecr.io/ms-products:1.0
    ports:
      - 3001:3001
    networks:
      - micro_service

networks:
  micro_service:
    external:
      name: micro_service